import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import {
  Activity, AlertTriangle, CalendarClock, CheckCircle2, Clock3, DatabaseBackup, FileKey2,
  Gauge, Globe2, HeartPulse, Languages, LockKeyhole, Plus, RefreshCw, Save, ShieldAlert,
  ShieldCheck, SlidersHorizontal, X
} from 'lucide-react';
import { useApp } from '../../app/AppProvider';
import { platformService } from './platformService';
import type {
  CapacitySnapshot, ContinuitySnapshot, Phase33Dashboard, PlatformIncident, PrivacyRequestRecord,
  PublicStatusSnapshot, RegionalSettingsSnapshot, RetentionSnapshot, SecurityPostureSnapshot
} from './types';

type JsonRecord = Record<string, unknown>;

function useLoad<T>(loader: () => Promise<T>, deps: readonly unknown[] = []) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [revision, setRevision] = useState(0);
  const reload = useCallback(() => setRevision((value) => value + 1), []);
  useEffect(() => {
    let mounted = true;
    setLoading(true); setError('');
    void loader().then((value) => { if (mounted) setData(value); }).catch((cause: unknown) => { if (mounted) setError(cause instanceof Error ? cause.message : 'No fue posible cargar la información.'); }).finally(() => { if (mounted) setLoading(false); });
    return () => { mounted = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...deps, revision]);
  return { data, loading, error, reload };
}

function formatDate(value: unknown, withTime = true) {
  if (!value) return '—';
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) return String(value);
  return new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', ...(withTime ? { timeStyle: 'short' as const } : {}) }).format(date);
}
function formatNumber(value: unknown) { return new Intl.NumberFormat('es-CO').format(Number(value || 0)); }
function formatBytes(value: unknown) {
  let number = Number(value || 0); const units = ['B', 'KB', 'MB', 'GB', 'TB']; let index = 0;
  while (number >= 1024 && index < units.length - 1) { number /= 1024; index += 1; }
  return `${number.toFixed(index === 0 ? 0 : number >= 10 ? 1 : 2)} ${units[index]}`;
}
function statusLabel(value: unknown) {
  const labels: Record<string, string> = {
    operational: 'Operativo', degraded: 'Degradado', partial_outage: 'Interrupción parcial', major_outage: 'Interrupción mayor', maintenance: 'Mantenimiento',
    investigating: 'Investigando', identified: 'Identificado', monitoring: 'Monitoreando', resolved: 'Resuelto', cancelled: 'Cancelado',
    received: 'Recibida', identity_verification: 'Verificación de identidad', in_review: 'En revisión', waiting_requester: 'Esperando titular', approved: 'Aprobada', partially_approved: 'Aprobada parcialmente', rejected: 'Rechazada', completed: 'Completada',
    passed: 'Aprobada', warning: 'Con advertencias', failed: 'Fallida', open: 'Abierto', accepted: 'Riesgo aceptado', false_positive: 'Falso positivo'
  };
  return labels[String(value)] || String(value || 'Sin estado');
}
function tone(value: unknown) {
  const status = String(value);
  if (['operational', 'resolved', 'completed', 'passed'].includes(status)) return 'success';
  if (['degraded', 'identified', 'monitoring', 'warning', 'in_review', 'waiting_requester'].includes(status)) return 'warning';
  if (['partial_outage', 'major_outage', 'critical', 'failed', 'open'].includes(status)) return 'danger';
  return 'info';
}
function PageHead({ title, description, actions }: { title: string; description: string; actions?: ReactNode }) {
  return <header className="platform-page-head"><div><span className="eyebrow">Orkesta · Fase 3.3</span><h1>{title}</h1><p>{description}</p></div>{actions ? <div className="platform-page-actions">{actions}</div> : null}</header>;
}
function Loading({ text = 'Cargando...' }: { text?: string }) { return <section className="platform-loading card"><RefreshCw className="spin" /><strong>{text}</strong></section>; }
function ErrorBox({ message, reload }: { message: string; reload: () => void }) { return <section className="platform-error card"><AlertTriangle /><div><strong>No fue posible cargar el módulo</strong><p>{message}</p></div><button className="btn btn-white" onClick={reload}>Reintentar</button></section>; }
function Metric({ icon, label, value, helper }: { icon: ReactNode; label: string; value: ReactNode; helper?: string }) { return <article className="platform-metric card"><div className="platform-metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong>{helper ? <small>{helper}</small> : null}</div></article>; }
function Modal({ title, subtitle, close, children }: { title: string; subtitle: string; close: () => void; children: ReactNode }) { return <div className="platform-modal-backdrop"><section className="card platform-modal phase33-modal"><header><div><span className="eyebrow">Fase 3.3</span><h2>{title}</h2><p>{subtitle}</p></div><button onClick={close}><X /></button></header>{children}</section></div>; }

export function PlatformReliabilityPage() {
  const { data, loading, error, reload } = useLoad<Phase33Dashboard>(() => platformService.getPhase33Dashboard(), []);
  const [maintenanceOpen, setMaintenanceOpen] = useState(false);
  if (loading && !data) return <div className="platform-page"><Loading text="Calculando salud de la plataforma..." /></div>;
  if (error && !data) return <div className="platform-page"><ErrorBox message={error} reload={reload} /></div>;
  const health = data?.health;
  const capacity = (data?.capacity || {}) as JsonRecord;
  return <div className="platform-page phase33-page">
    <PageHead title="Salud, capacidad y disponibilidad" description="Vista ejecutiva de la operación, componentes, capacidad e indicadores de continuidad." actions={<><Link to="/status" className="btn btn-white"><Globe2 size={16} />Estado público</Link><button className="btn btn-primary" onClick={() => setMaintenanceOpen(true)}><CalendarClock size={16} />Programar mantenimiento</button></>} />
    <section className="phase33-health-hero card">
      <div className={`phase33-score ${tone(health?.status)}`}><strong>{health?.healthScore ?? 0}</strong><span>/100</span></div>
      <div><span className={`platform-chip ${tone(health?.status)}`}>{statusLabel(health?.status)}</span><h2>Estado general de Orkesta</h2><p>Última medición: {formatDate(health?.createdAt)}</p></div>
      <button className="btn btn-white" onClick={reload}><RefreshCw size={16} />Actualizar</button>
    </section>
    <section className="platform-metrics-grid">
      <Metric icon={<ShieldAlert />} label="Incidentes activos" value={data?.incidents.active || 0} helper={`${data?.incidents.critical || 0} críticos`} />
      <Metric icon={<FileKey2 />} label="Privacidad pendiente" value={data?.privacy.open || 0} helper={`${data?.privacy.overdue || 0} vencidas`} />
      <Metric icon={<DatabaseBackup />} label="Sin backup reciente" value={data?.continuity.organizationsWithoutRecentBackup || 0} helper={`${data?.continuity.failedVerifications || 0} verificaciones fallidas`} />
      <Metric icon={<LockKeyhole />} label="Hallazgos de seguridad" value={data?.security.openFindings || 0} helper={`${data?.security.highFindings || 0} altos o críticos`} />
      <Metric icon={<Gauge />} label="Casos almacenados" value={formatNumber(capacity.casesTotal)} helper={formatBytes(capacity.storageBytes)} />
      <Metric icon={<Activity />} label="API últimas 24 h" value={formatNumber(capacity.apiRequests24h)} helper={`${formatNumber(capacity.jobsFailed24h)} trabajos fallidos`} />
    </section>
    <section className="phase33-two-columns">
      <article className="card phase33-panel"><header><div><h2>Componentes</h2><p>Estado calculado por el scheduler central.</p></div><HeartPulse /></header><div className="phase33-component-list">{(health?.components || []).map((item) => <div key={item.code}><span className={`phase33-dot ${tone(item.status)}`} /><div><strong>{item.name}</strong><small>{item.message || 'Sin alertas'}</small></div><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></div>)}</div></article>
      <article className="card phase33-panel"><header><div><h2>Actividad reciente</h2><p>Incidentes y mantenimientos visibles.</p></div><Clock3 /></header>{(data?.incidents.recent || []).slice(0, 5).map((incident) => <div className="phase33-list-row" key={incident.id}><div><strong>{incident.incidentNumber} · {incident.title}</strong><small>{formatDate(incident.startedAt)}</small></div><span className={`platform-chip ${tone(incident.status)}`}>{statusLabel(incident.status)}</span></div>)}{!(data?.incidents.recent || []).length ? <p className="phase33-empty">No hay incidentes registrados.</p> : null}{(data?.maintenance || []).map((item) => <div className="phase33-list-row" key={String(item.id)}><div><strong>{String(item.title || 'Mantenimiento')}</strong><small>{formatDate(item.startsAt)} – {formatDate(item.endsAt)}</small></div><span className="platform-chip info">{statusLabel(item.status)}</span></div>)}</article>
    </section>
    {maintenanceOpen ? <MaintenanceModal close={() => setMaintenanceOpen(false)} saved={() => { setMaintenanceOpen(false); reload(); }} /> : null}
  </div>;
}

function MaintenanceModal({ close, saved }: { close: () => void; saved: () => void }) {
  const [title, setTitle] = useState('Mantenimiento programado'); const [description, setDescription] = useState('');
  const [startsAt, setStartsAt] = useState(''); const [endsAt, setEndsAt] = useState(''); const [components, setComponents] = useState('web_app,database');
  const [reason, setReason] = useState('Programación de mantenimiento de plataforma'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await platformService.upsertPhase33Maintenance({ title, description, status: 'scheduled', affectedComponentCodes: components.split(',').map((item) => item.trim()).filter(Boolean), affectedOrganizationIds: [], isPublic: true, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString() }, reason); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible programar el mantenimiento.'); } finally { setSaving(false); } }
  return <Modal title="Programar mantenimiento" subtitle="El estado público mostrará esta ventana y el scheduler administrará su vigencia." close={close}><form className="phase33-form" onSubmit={submit}><label>Título<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label>Descripción<textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="platform-form-grid"><label>Inicio<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} required /></label><label>Fin<input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} required /></label></div><label>Componentes, separados por coma<input value={components} onChange={(event) => setComponents(event.target.value)} /></label><label>Justificación<textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} required /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Programar'}</button></footer></form></Modal>;
}

export function PlatformIncidentsPage() {
  const { data, loading, error, reload } = useLoad<PlatformIncident[]>(() => platformService.listPhase33Incidents(true), []);
  const [editing, setEditing] = useState<PlatformIncident | null | undefined>(undefined);
  if (loading && !data) return <div className="platform-page"><Loading text="Cargando incidentes..." /></div>;
  return <div className="platform-page phase33-page"><PageHead title="Gestión de incidentes" description="Registro operativo, línea de tiempo, causa raíz y comunicación pública." actions={<button className="btn btn-primary" onClick={() => setEditing(null)}><Plus size={16} />Nuevo incidente</button>} />{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="phase33-incident-grid">{(data || []).map((incident) => <article className="card phase33-incident-card" key={incident.id}><header><span className={`platform-chip ${tone(incident.severity === 'critical' ? 'critical' : incident.status)}`}>{incident.severity.toUpperCase()}</span><span className={`platform-chip ${tone(incident.status)}`}>{statusLabel(incident.status)}</span></header><h2>{incident.title}</h2><p>{incident.summary || 'Sin resumen.'}</p><div className="phase33-incident-meta"><span>{incident.incidentNumber}</span><span>{formatDate(incident.startedAt)}</span><span>{incident.isPublic ? 'Público' : 'Interno'}</span></div><div className="phase33-update-list">{incident.updates.slice(0, 3).map((update) => <div key={update.id}><strong>{statusLabel(update.status)}</strong><span>{update.message}</span><small>{formatDate(update.createdAt)}</small></div>)}</div><footer><button className="btn btn-white compact" onClick={() => setEditing(incident)}>Gestionar</button></footer></article>)}</section>{editing !== undefined ? <IncidentModal incident={editing} close={() => setEditing(undefined)} saved={() => { setEditing(undefined); reload(); }} /> : null}</div>;
}

function IncidentModal({ incident, close, saved }: { incident: PlatformIncident | null; close: () => void; saved: () => void }) {
  const [title, setTitle] = useState(incident?.title || ''); const [summary, setSummary] = useState(incident?.summary || '');
  const [severity, setSeverity] = useState(incident?.severity || 'minor'); const [status, setStatus] = useState(incident?.status || 'investigating'); const [impact, setImpact] = useState(incident?.impact || 'degraded');
  const [publicVisible, setPublicVisible] = useState(incident?.isPublic ?? true); const [updateMessage, setUpdateMessage] = useState(''); const [reason, setReason] = useState('Gestión operativa del incidente'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const id = await platformService.upsertPhase33Incident({ id: incident?.id || null, title, summary, severity, status, impact, affectedComponentCodes: incident?.affectedComponentCodes || ['web_app'], affectedOrganizationIds: incident?.affectedOrganizationIds || [], isPublic: publicVisible }, reason); if (updateMessage.trim()) await platformService.addPhase33IncidentUpdate(id, status, updateMessage, publicVisible); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar el incidente.'); } finally { setSaving(false); } }
  return <Modal title={incident ? `Gestionar ${incident.incidentNumber}` : 'Nuevo incidente'} subtitle="Toda modificación queda auditada y puede publicarse en la página de estado." close={close}><form className="phase33-form" onSubmit={submit}><label>Título<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label>Resumen<textarea rows={3} value={summary} onChange={(event) => setSummary(event.target.value)} /></label><div className="platform-form-grid"><label>Severidad<select value={severity} onChange={(event) => setSeverity(event.target.value as typeof severity)}><option value="minor">Menor</option><option value="major">Mayor</option><option value="critical">Crítica</option></select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="investigating">Investigando</option><option value="identified">Identificado</option><option value="monitoring">Monitoreando</option><option value="resolved">Resuelto</option><option value="cancelled">Cancelado</option></select></label><label>Impacto<select value={impact} onChange={(event) => setImpact(event.target.value as typeof impact)}><option value="none">Sin impacto</option><option value="degraded">Degradado</option><option value="partial_outage">Interrupción parcial</option><option value="major_outage">Interrupción mayor</option></select></label></div><label>Actualización para la línea de tiempo<textarea rows={3} value={updateMessage} onChange={(event) => setUpdateMessage(event.target.value)} placeholder="Opcional" /></label><label className="commercial-check"><input type="checkbox" checked={publicVisible} onChange={(event) => setPublicVisible(event.target.checked)} />Visible públicamente</label><label>Justificación<textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} required /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Guardar incidente'}</button></footer></form></Modal>;
}

export function PlatformPrivacyPage() {
  const { data, loading, error, reload } = useLoad<PrivacyRequestRecord[]>(() => platformService.listPhase33PrivacyRequests(), []);
  const [editing, setEditing] = useState<PrivacyRequestRecord | null | undefined>(undefined);
  const overdue = useMemo(() => (data || []).filter((item) => !['completed', 'cancelled', 'rejected'].includes(item.status) && new Date(item.dueAt) < new Date()).length, [data]);
  if (loading && !data) return <div className="platform-page"><Loading text="Cargando solicitudes de privacidad..." /></div>;
  return <div className="platform-page phase33-page"><PageHead title="Privacidad y derechos de titulares" description="Solicitudes de acceso, corrección, portabilidad, eliminación, oposición y retiro de consentimiento." actions={<button className="btn btn-primary" onClick={() => setEditing(null)}><Plus size={16} />Registrar solicitud</button>} /><section className="platform-metrics-grid"><Metric icon={<FileKey2 />} label="Solicitudes totales" value={(data || []).length} /><Metric icon={<Clock3 />} label="Vencidas" value={overdue} /><Metric icon={<CheckCircle2 />} label="Completadas" value={(data || []).filter((item) => item.status === 'completed').length} /></section>{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="card platform-table-card"><table className="platform-table"><thead><tr><th>Solicitud</th><th>Organización</th><th>Titular</th><th>Tipo</th><th>Vencimiento</th><th>Estado</th><th /></tr></thead><tbody>{(data || []).map((item) => <tr key={item.id}><td><strong>{item.requestNumber}</strong><small>{formatDate(item.createdAt)}</small></td><td>{item.organizationName || '—'}</td><td><strong>{item.requesterName}</strong><small>{item.requesterEmail}</small></td><td>{statusLabel(item.requestType)}</td><td className={new Date(item.dueAt) < new Date() && !['completed', 'cancelled', 'rejected'].includes(item.status) ? 'text-danger' : ''}>{formatDate(item.dueAt)}</td><td><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></td><td><button className="btn btn-white compact" onClick={() => setEditing(item)}>Gestionar</button></td></tr>)}</tbody></table></section>{editing !== undefined ? <PrivacyModal request={editing} close={() => setEditing(undefined)} saved={() => { setEditing(undefined); reload(); }} /> : null}</div>;
}

function PrivacyModal({ request, close, saved }: { request: PrivacyRequestRecord | null; close: () => void; saved: () => void }) {
  const [organizationId, setOrganizationId] = useState(request?.organizationId || ''); const [requestType, setRequestType] = useState(request?.requestType || 'access'); const [status, setStatus] = useState(request?.status || 'received'); const [priority, setPriority] = useState(request?.priority || 'normal'); const [name, setName] = useState(request?.requesterName || ''); const [email, setEmail] = useState(request?.requesterEmail || ''); const [document, setDocument] = useState(request?.requesterDocument || ''); const [description, setDescription] = useState(request?.description || ''); const [decision, setDecision] = useState(request?.decision || ''); const [decisionReason, setDecisionReason] = useState(request?.decisionReason || ''); const [reason, setReason] = useState('Actualización de solicitud de privacidad'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await platformService.upsertPhase33PrivacyRequest({ id: request?.id || null, organizationId, requestType, status, priority, requesterName: name, requesterEmail: email, requesterDocument: document, description, decision, decisionReason, identityVerified: status !== 'identity_verification' }, reason); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la solicitud.'); } finally { setSaving(false); } }
  return <Modal title={request ? `Gestionar ${request.requestNumber}` : 'Registrar solicitud'} subtitle="Use el UUID de la organización cuando la solicitud sea creada desde el Super Admin." close={close}><form className="phase33-form" onSubmit={submit}>{!request ? <label>ID de la organización<input value={organizationId} onChange={(event) => setOrganizationId(event.target.value)} required /></label> : null}<div className="platform-form-grid"><label>Tipo<select value={requestType} onChange={(event) => setRequestType(event.target.value)}><option value="access">Acceso</option><option value="correction">Corrección</option><option value="portability">Portabilidad</option><option value="deletion">Eliminación</option><option value="restriction">Restricción</option><option value="objection">Oposición</option><option value="consent_withdrawal">Retiro de consentimiento</option></select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="received">Recibida</option><option value="identity_verification">Verificación de identidad</option><option value="in_review">En revisión</option><option value="waiting_requester">Esperando titular</option><option value="approved">Aprobada</option><option value="partially_approved">Aprobada parcialmente</option><option value="rejected">Rechazada</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select></label><label>Prioridad<select value={priority} onChange={(event) => setPriority(event.target.value)}><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><div className="platform-form-grid"><label>Nombre<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Correo<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Documento<input value={document} onChange={(event) => setDocument(event.target.value)} /></label></div><label>Descripción<textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} required /></label>{request ? <><label>Decisión<textarea rows={2} value={decision} onChange={(event) => setDecision(event.target.value)} /></label><label>Motivo de la decisión<textarea rows={2} value={decisionReason} onChange={(event) => setDecisionReason(event.target.value)} /></label></> : null}<label>Justificación interna<textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} required /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Guardar'}</button></footer></form></Modal>;
}

export function PlatformGovernancePage() {
  const organizations = useLoad(() => platformService.listOrganizations({ page: 1, pageSize: 100 }), []);
  const [organizationId, setOrganizationId] = useState(''); const [tab, setTab] = useState<'continuity' | 'retention' | 'security' | 'regional'>('continuity');
  useEffect(() => { if (!organizationId && organizations.data?.rows[0]) setOrganizationId(organizations.data.rows[0].id); }, [organizationId, organizations.data]);
  return <div className="platform-page phase33-page"><PageHead title="Gobierno, continuidad y cumplimiento" description="RPO/RTO, retención, postura de seguridad y configuración regional por organización." /><section className="card phase33-governance-toolbar"><label>Organización<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{organizations.data?.rows.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select></label><div>{(['continuity','retention','security','regional'] as const).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item === 'continuity' ? 'Continuidad' : item === 'retention' ? 'Retención' : item === 'security' ? 'Seguridad' : 'Región'}</button>)}</div></section>{!organizationId ? <Loading text="Cargando organizaciones..." /> : tab === 'continuity' ? <ContinuityPanel organizationId={organizationId} /> : tab === 'retention' ? <RetentionPanel organizationId={organizationId} /> : tab === 'security' ? <SecurityPanel /> : <RegionalPanel organizationId={organizationId} />}</div>;
}

function ContinuityPanel({ organizationId }: { organizationId: string }) {
  const { data, loading, error, reload } = useLoad<ContinuitySnapshot>(() => platformService.getPhase33Continuity(organizationId), [organizationId]);
  const policy = (data?.policies[0] || {}) as JsonRecord; const [editing, setEditing] = useState(false);
  if (loading && !data) return <Loading text="Cargando continuidad..." />;
  return <section className="phase33-two-columns"><article className="card phase33-panel"><header><div><h2>Objetivos de recuperación</h2><p>Compromisos internos por organización.</p></div><DatabaseBackup /></header>{error ? <ErrorBox message={error} reload={reload} /> : null}<div className="phase33-kv"><span>RPO</span><strong>{formatNumber(policy.rpoMinutes)} minutos</strong><span>RTO</span><strong>{formatNumber(policy.rtoMinutes)} minutos</strong><span>Frecuencia de verificación</span><strong>{formatNumber(policy.verificationFrequencyDays)} días</strong><span>Última verificación</span><strong>{formatDate(policy.lastVerifiedBackupAt)}</strong><span>Próxima verificación</span><strong>{formatDate(policy.nextVerificationAt)}</strong></div><button className="btn btn-primary" onClick={() => setEditing(true)}><SlidersHorizontal size={16} />Editar política</button></article><article className="card phase33-panel"><header><div><h2>Verificaciones de backup</h2><p>Control de metadatos, manifiesto y objeto en Storage.</p></div><ShieldCheck /></header>{(data?.verifications || []).slice(0, 10).map((item) => <div className="phase33-list-row" key={String(item.id)}><div><strong>{String(item.organizationName || '')}</strong><small>{formatDate(item.startedAt)}</small></div><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></div>)}{!data?.verifications.length ? <p className="phase33-empty">Aún no hay verificaciones.</p> : null}</article>{editing ? <ContinuityModal organizationId={organizationId} policy={policy} close={() => setEditing(false)} saved={() => { setEditing(false); reload(); }} /> : null}</section>;
}
function ContinuityModal({ organizationId, policy, close, saved }: { organizationId: string; policy: JsonRecord; close: () => void; saved: () => void }) {
  const [rpo, setRpo] = useState(String(policy.rpoMinutes || 1440)); const [rto, setRto] = useState(String(policy.rtoMinutes || 480)); const [frequency, setFrequency] = useState(String(policy.verificationFrequencyDays || 30)); const [owner, setOwner] = useState(String(policy.continuityOwnerEmail || '')); const [notes, setNotes] = useState(String(policy.notes || '')); const [reason, setReason] = useState('Actualización de objetivos de continuidad'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await platformService.upsertPhase33ContinuityPolicy(organizationId, { rpoMinutes: Number(rpo), rtoMinutes: Number(rto), verificationFrequencyDays: Number(frequency), requireRestoreApproval: true, requireTwoPersonApproval: true, continuityOwnerEmail: owner, notes }, reason); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la política.'); } finally { setSaving(false); } }
  return <Modal title="Política de continuidad" subtitle="RPO: pérdida máxima tolerada. RTO: tiempo objetivo de recuperación." close={close}><form className="phase33-form" onSubmit={submit}><div className="platform-form-grid"><label>RPO en minutos<input type="number" min="15" value={rpo} onChange={(event) => setRpo(event.target.value)} /></label><label>RTO en minutos<input type="number" min="15" value={rto} onChange={(event) => setRto(event.target.value)} /></label><label>Verificar cada N días<input type="number" min="1" value={frequency} onChange={(event) => setFrequency(event.target.value)} /></label></div><label>Responsable de continuidad<input type="email" value={owner} onChange={(event) => setOwner(event.target.value)} /></label><label>Notas<textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><label>Justificación<textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Guardar'}</button></footer></form></Modal>;
}

function RetentionPanel({ organizationId }: { organizationId: string }) {
  const { data, loading, error, reload } = useLoad<RetentionSnapshot>(() => platformService.getPhase33Retention(organizationId), [organizationId]); const [preview, setPreview] = useState<JsonRecord | null>(null); const [running, setRunning] = useState(false);
  async function runPreview() { setRunning(true); try { const result = await platformService.previewPhase33Retention(organizationId, 'Simulación de retención desde Fase 3.3'); setPreview(result); reload(); } finally { setRunning(false); } }
  if (loading && !data) return <Loading text="Cargando retención..." />;
  return <section><div className="phase33-section-actions"><div><h2>Políticas de retención</h2><p>La fase 3.3 opera en modo seguro: previsualiza y no elimina automáticamente.</p></div><button className="btn btn-primary" disabled={running} onClick={() => void runPreview()}><ShieldCheck size={16} />{running ? 'Calculando...' : 'Ejecutar simulación'}</button></div>{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="phase33-retention-grid">{(data?.policies || []).map((item) => <article className="card" key={String(item.id)}><span className={`platform-chip ${item.enabled ? 'success' : 'info'}`}>{item.enabled ? 'Activa' : 'Inactiva'}</span><h3>{String(item.dataDomain)}</h3><strong>{formatNumber(item.retentionDays)} días</strong><p>Acción: {String(item.action)} · aprobación: {item.requireApproval ? 'sí' : 'no'}</p></article>)}</section>{preview ? <article className="card phase33-preview"><h2>Resultado de la simulación</h2><pre>{JSON.stringify(preview.results || preview, null, 2)}</pre><div className="alert warning">No se eliminó ningún registro. Cualquier ejecución destructiva requiere una revisión adicional.</div></article> : null}</section>;
}

function SecurityPanel() {
  const { data, loading, error, reload } = useLoad<SecurityPostureSnapshot>(() => platformService.getPhase33SecurityPosture(), []);
  if (loading && !data) return <Loading text="Calculando postura de seguridad..." />;
  return <section><section className="phase33-health-hero card"><div className={`phase33-score ${Number(data?.score || 0) >= 80 ? 'success' : Number(data?.score || 0) >= 60 ? 'warning' : 'danger'}`}><strong>{data?.score || 0}</strong><span>/100</span></div><div><h2>Postura de seguridad</h2><p>{data?.open || 0} hallazgos abiertos. La puntuación se actualiza con el scheduler.</p></div><button className="btn btn-white" onClick={reload}><RefreshCw size={16} />Actualizar</button></section>{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="phase33-finding-grid">{(data?.findings || []).map((item) => <article className="card" key={String(item.id)}><header><span className={`platform-chip ${tone(item.severity)}`}>{String(item.severity).toUpperCase()}</span><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></header><h3>{String(item.title)}</h3><p>{String(item.description)}</p><small>{String(item.recommendation || '')}</small>{item.status === 'open' ? <button className="btn btn-white compact" onClick={async () => { const notes = window.prompt('Notas de resolución o aceptación:'); if (!notes) return; await platformService.resolvePhase33SecurityFinding(String(item.id), 'resolved', notes); reload(); }}>Marcar resuelto</button> : null}</article>)}</section></section>;
}

function RegionalPanel({ organizationId }: { organizationId: string }) {
  const { data, loading, error, reload } = useLoad<RegionalSettingsSnapshot>(() => platformService.getPhase33RegionalSettings(organizationId), [organizationId]); const [editing, setEditing] = useState(false);
  if (loading && !data) return <Loading text="Cargando configuración regional..." />;
  return <section className="phase33-two-columns"><article className="card phase33-panel"><header><div><h2>Configuración regional</h2><p>Base para internacionalización y calendarios laborales.</p></div><Languages /></header>{error ? <ErrorBox message={error} reload={reload} /> : null}<div className="phase33-kv"><span>Idioma y locale</span><strong>{data?.language} · {data?.locale}</strong><span>País</span><strong>{data?.countryCode}</strong><span>Zona horaria</span><strong>{data?.timezone}</strong><span>Moneda</span><strong>{data?.currency}</strong><span>Fecha y hora</span><strong>{data?.dateFormat} · {data?.timeFormat}</strong><span>Días laborales</span><strong>{data?.businessDays?.join(', ')}</strong></div><button className="btn btn-primary" onClick={() => setEditing(true)}><Save size={16} />Editar</button></article><article className="card phase33-panel"><header><div><h2>Alcance actual</h2><p>Preparación regional sin traducción automática del contenido existente.</p></div><Globe2 /></header><div className="alert info">El idioma, la moneda, la zona horaria y los calendarios ya son configurables. La traducción completa de todos los textos históricos requiere una fase de i18n específica.</div></article>{editing && data ? <RegionalModal organizationId={organizationId} data={data} close={() => setEditing(false)} saved={() => { setEditing(false); reload(); }} /> : null}</section>;
}
function RegionalModal({ organizationId, data, close, saved }: { organizationId: string; data: RegionalSettingsSnapshot; close: () => void; saved: () => void }) {
  const [locale, setLocale] = useState(data.locale); const [language, setLanguage] = useState(data.language); const [countryCode, setCountryCode] = useState(data.countryCode); const [timezone, setTimezone] = useState(data.timezone); const [currency, setCurrency] = useState(data.currency); const [dateFormat, setDateFormat] = useState(data.dateFormat); const [timeFormat, setTimeFormat] = useState(data.timeFormat); const [reason, setReason] = useState('Actualización de configuración regional'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await platformService.upsertPhase33RegionalSettings(organizationId, { locale, language, countryCode, timezone, currency, dateFormat, timeFormat, firstDayOfWeek: data.firstDayOfWeek, businessDays: data.businessDays, translations: data.translations }, reason); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la configuración.'); } finally { setSaving(false); } }
  return <Modal title="Configuración regional" subtitle="Valores usados para fechas, moneda, zona horaria y experiencia regional." close={close}><form className="phase33-form" onSubmit={submit}><div className="platform-form-grid"><label>Locale<input value={locale} onChange={(event) => setLocale(event.target.value)} /></label><label>Idioma<input value={language} onChange={(event) => setLanguage(event.target.value)} /></label><label>País<input maxLength={2} value={countryCode} onChange={(event) => setCountryCode(event.target.value.toUpperCase())} /></label><label>Zona horaria<input value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><label>Moneda<input maxLength={3} value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} /></label><label>Formato de fecha<input value={dateFormat} onChange={(event) => setDateFormat(event.target.value)} /></label><label>Formato de hora<select value={timeFormat} onChange={(event) => setTimeFormat(event.target.value as '12h' | '24h')}><option value="12h">12 horas</option><option value="24h">24 horas</option></select></label></div><label>Justificación<textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Guardar'}</button></footer></form></Modal>;
}

export function PlatformCapacityPage() {
  const { data, loading, error, reload } = useLoad<CapacitySnapshot>(() => platformService.getPhase33Capacity(), []); const current = (data?.current || {}) as JsonRecord;
  if (loading && !data) return <div className="platform-page"><Loading text="Cargando capacidad..." /></div>;
  return <div className="platform-page phase33-page"><PageHead title="Capacidad y crecimiento" description="Consumo agregado, uso por organización y señales de capacidad." actions={<button className="btn btn-white" onClick={reload}><RefreshCw size={16} />Actualizar</button>} /><section className="platform-metrics-grid"><Metric icon={<Globe2 />} label="Organizaciones" value={formatNumber(current.organizationsTotal)} /><Metric icon={<Gauge />} label="Usuarios" value={formatNumber(current.usersTotal)} /><Metric icon={<Activity />} label="Casos" value={formatNumber(current.casesTotal)} /><Metric icon={<DatabaseBackup />} label="Almacenamiento" value={formatBytes(current.storageBytes)} /><Metric icon={<HeartPulse />} label="Solicitudes API 24 h" value={formatNumber(current.apiRequests24h)} /><Metric icon={<AlertTriangle />} label="Trabajos fallidos 24 h" value={formatNumber(current.jobsFailed24h)} /></section>{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="card platform-table-card"><table className="platform-table"><thead><tr><th>Organización</th><th>Usuarios</th><th>Activos</th><th>Casos</th><th>Almacenamiento</th><th>Correos</th><th>Automatizaciones</th></tr></thead><tbody>{(data?.organizations || []).map((item) => <tr key={String(item.organizationId)}><td><strong>{String(item.organizationName)}</strong></td><td>{formatNumber(item.usersTotal)}</td><td>{formatNumber(item.usersActive)}</td><td>{formatNumber(item.casesTotal)}</td><td>{formatBytes(item.storageBytes)}</td><td>{formatNumber(item.emailsSent)}</td><td>{formatNumber(item.automationsExecuted)}</td></tr>)}</tbody></table></section></div>;
}

export function PublicStatusPage() {
  const { data, loading, error, reload } = useLoad<PublicStatusSnapshot>(() => platformService.getPublicStatus(), []);
  if (loading && !data) return <main className="phase33-public-status"><Loading text="Consultando estado de Orkesta..." /></main>;
  return <main className="phase33-public-status"><header><Link to="/">Orkesta</Link><span>Estado del servicio</span></header><section className={`phase33-status-banner ${tone(data?.overallStatus)}`}><div><HeartPulse /><h1>{statusLabel(data?.overallStatus)}</h1><p>Última actualización: {formatDate(data?.updatedAt)}</p></div><button className="btn btn-white" onClick={reload}><RefreshCw size={16} />Actualizar</button></section>{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="card phase33-status-components"><h2>Componentes</h2>{(data?.components || []).map((item) => <div key={item.code}><div><span className={`phase33-dot ${tone(item.status)}`} /><strong>{item.name}</strong></div><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></div>)}</section><section className="phase33-status-grid"><article className="card"><h2>Incidentes recientes</h2>{(data?.incidents || []).map((incident) => <div className="phase33-status-incident" key={incident.id || incident.incidentNumber}><header><strong>{incident.title}</strong><span className={`platform-chip ${tone(incident.status)}`}>{statusLabel(incident.status)}</span></header><p>{incident.summary}</p><small>{formatDate(incident.startedAt)}</small></div>)}{!data?.incidents.length ? <p>Sin incidentes reportados.</p> : null}</article><article className="card"><h2>Mantenimientos</h2>{(data?.maintenance || []).map((item) => <div className="phase33-status-incident" key={String(item.id || item.title)}><strong>{String(item.title)}</strong><p>{String(item.description || '')}</p><small>{formatDate(item.startsAt)} – {formatDate(item.endsAt)}</small></div>)}{!data?.maintenance.length ? <p>No hay mantenimientos programados.</p> : null}</article></section></main>;
}

export function OrganizationPrivacyPage() {
  const { currentUser } = useApp(); const { data, loading, error, reload } = useLoad<PrivacyRequestRecord[]>(() => platformService.listOrganizationPrivacyRequests(), []); const [open, setOpen] = useState(false);
  if (loading && !data) return <main className="page"><Loading text="Cargando privacidad..." /></main>;
  return <div className="page phase33-page"><PageHead title="Privacidad y datos personales" description="Registra y consulta solicitudes relacionadas con los datos administrados por la organización." actions={<button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16} />Nueva solicitud</button>} />{error ? <ErrorBox message={error} reload={reload} /> : null}<section className="phase33-privacy-user-grid">{(data || []).map((item) => <article className="card" key={item.id}><header><strong>{item.requestNumber}</strong><span className={`platform-chip ${tone(item.status)}`}>{statusLabel(item.status)}</span></header><h3>{statusLabel(item.requestType)}</h3><p>{item.description}</p><footer><span>Vence: {formatDate(item.dueAt)}</span><span>{item.requesterEmail}</span></footer></article>)}</section>{open ? <OrganizationPrivacyModal defaultName={currentUser?.name || ''} defaultEmail={currentUser?.email || ''} close={() => setOpen(false)} saved={() => { setOpen(false); reload(); }} /> : null}</div>;
}
function OrganizationPrivacyModal({ defaultName, defaultEmail, close, saved }: { defaultName: string; defaultEmail: string; close: () => void; saved: () => void }) {
  const [requestType, setRequestType] = useState('access'); const [name, setName] = useState(defaultName); const [email, setEmail] = useState(defaultEmail); const [document, setDocument] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await platformService.createOrganizationPrivacyRequest({ requestType, requesterName: name, requesterEmail: email, requesterDocument: document, description }); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible registrar la solicitud.'); } finally { setSaving(false); } }
  return <Modal title="Nueva solicitud de privacidad" subtitle="La solicitud quedará disponible para el equipo autorizado y el Super Admin." close={close}><form className="phase33-form" onSubmit={submit}><label>Tipo<select value={requestType} onChange={(event) => setRequestType(event.target.value)}><option value="access">Acceso</option><option value="correction">Corrección</option><option value="portability">Portabilidad</option><option value="deletion">Eliminación</option><option value="restriction">Restricción</option><option value="objection">Oposición</option><option value="consent_withdrawal">Retiro de consentimiento</option></select></label><div className="platform-form-grid"><label>Nombre<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Correo<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Documento<input value={document} onChange={(event) => setDocument(event.target.value)} /></label></div><label>Descripción<textarea rows={5} value={description} onChange={(event) => setDescription(event.target.value)} required /></label>{error ? <div className="alert danger">{error}</div> : null}<footer><button type="button" className="btn btn-white" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Enviando...' : 'Registrar solicitud'}</button></footer></form></Modal>;
}

export function OrganizationRegionalPage() {
  const { data, loading, error, reload } = useLoad<RegionalSettingsSnapshot>(() => platformService.getOrganizationRegionalSettings(), []); const [saving, setSaving] = useState(false); const [form, setForm] = useState<RegionalSettingsSnapshot | null>(null);
  useEffect(() => { if (data) setForm(data); }, [data]);
  if (loading && !form) return <main className="page"><Loading text="Cargando configuración regional..." /></main>;
  async function save() { if (!form) return; setSaving(true); try { await platformService.updateOrganizationRegionalSettings(form as unknown as JsonRecord); reload(); } finally { setSaving(false); } }
  return <div className="page phase33-page"><PageHead title="Región e idioma" description="Configura la zona horaria, moneda y formatos predeterminados de la organización." actions={<button className="btn btn-primary" disabled={saving || !form} onClick={() => void save()}><Save size={16} />{saving ? 'Guardando...' : 'Guardar'}</button>} />{error ? <ErrorBox message={error} reload={reload} /> : null}{form ? <section className="card phase33-regional-form"><div className="platform-form-grid"><label>Locale<input value={form.locale} onChange={(event) => setForm({ ...form, locale: event.target.value })} /></label><label>Idioma<input value={form.language} onChange={(event) => setForm({ ...form, language: event.target.value })} /></label><label>País<input value={form.countryCode} maxLength={2} onChange={(event) => setForm({ ...form, countryCode: event.target.value.toUpperCase() })} /></label><label>Zona horaria<input value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /></label><label>Moneda<input value={form.currency} maxLength={3} onChange={(event) => setForm({ ...form, currency: event.target.value.toUpperCase() })} /></label><label>Formato de fecha<input value={form.dateFormat} onChange={(event) => setForm({ ...form, dateFormat: event.target.value })} /></label><label>Formato de hora<select value={form.timeFormat} onChange={(event) => setForm({ ...form, timeFormat: event.target.value as '12h' | '24h' })}><option value="12h">12 horas</option><option value="24h">24 horas</option></select></label></div><div className="alert info">Esta configuración prepara Orkesta para internacionalización. No traduce automáticamente textos ya registrados.</div></section> : null}</div>;
}
